globalProperties:
  apiTests: true
  modelTests: true
  gitUserId: getlago
  gitRepoId: lago-java-client

additionalProperties:
  developerName: Lago
  developerEmail: tech@getlago.com
  developerOrganization: Lago
  developerOrganizationUrl: https://getlago.com/

  licenseName: MIT
  licenseUrl: https://opensource.org/licenses/MIT

  artifactVersion: API_VERSION
  artifactId: lago-java-client
  artifactUrl: https://github.com/getlago/lago-java-client
  artifactDescription: Enable your Java application to interact with the Lago API

  apiPackage: com.getlago.api

  disallowAdditionalPropertiesIfNotPresent: false
