additionalProperties:
  gemAuthor: Lago
  gemAuthorEmail: tech@getlago.com
  gemDescription: Lago API allows your application to interact with the Lago API
  gemHomepage: https://github.com/getlago/lago-ruby
  gemLicense: MIT
  gemName: lago_ruby
  gemSummary: Ruby wrapper for the Lago API
  gemVersion: API_VERSION

  moduleName: LagoAPI
