globalProperties:
  apiTests: true
  modelTests: true
  gitUserId: getlago
  gitRepoId: lago-ruby
  appName: Lago API

additionalProperties:
  gemAuthor: Lago
  gemAuthorEmail: tech@getlago.com
  gemDescription: Enable your ruby application to interact with the Lago API
  gemHomepage: https://github.com/getlago/lago-ruby
  gemLicense: MIT
  gemName: lago_ruby
  gemSummary: Ruby wrapper for the Lago API
  gemVersion: API_VERSION

  docHomepage: https://doc.getlago.com
  lagoHomepage: https://www.getlago.com/

  moduleName: LagoAPI
