type: object
description: The custom billing settings for your organization.
properties:
  invoice_footer:
    type:
      - string
      - "null"
    example: "This is my customer footer"
    description: The customer invoice message that appears at the bottom of each billing documents.
  invoice_grace_period:
    type: integer
    example: 3
    description: The grace period, expressed in days, for finalizing the invoice. This period refers to the additional time granted to your customers beyond the invoice due date to adjust usage and line items. Can be overwritten by the customer's grace period.
  document_locale:
    type: string
    example: en
    description: The locale of the billing documents, expressed in the ISO 639-1 format. This field indicates the language or regional variant used for the documents content issued or the embeddable customer portal.
