name: Validate OpenAPI schema - ApiDOM

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/apidom-validate@v1
        with:
          definition-file: 'openapi.yaml'
