name: Validate OpenAPI schema - editor-next.swagger.io

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: 'swagger.yaml'
          swagger-editor-url: 'https://editor-next.swagger.io/'
