name: Validate OpenAPI schema - Spectral

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'swagger.yaml'
