name: Add tags

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Parse openapi.yaml version
        id: "parse-openapi"
        uses: jbutcher5/read-yaml@main
        with:
          file: './openapi.yaml'
          key-path: '["info", "version"]'

      - name: Display OpenAPI version
        run: echo "${{ steps.parse-openapi.outputs.data }}"

      - name: Add tag
        id: "add-tag"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.parse-openapi.outputs.data }}"
          tag_exists_error: false
